version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci4-app1
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci4-app2
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: ci4-webserver
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
